config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "homes#top"
  get "homes/about" => "homes#about", as: "about"

  resources :users, only: [:show, :index, :edit]
  
  resources :items, only: [:index, :new, :create]do
    resource :item_image
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image
  
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  
  belongs_to :item
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :items
  
  validates :item, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [
      :last_name,
      :first_name,
      :first_name_kana,
      :last_name_kana,
      :post_code,
      :address,
      :phone_number,
    ])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @item = Item.all
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:title, :body, item_images_images: [])
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @content=params[:content]
    @records=Item.where(is_active: 1).search_for(@content)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]

  def show
  end

  def index
  end

  def edit
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'guestuserでログインしました。'
  end

  private

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h2>わらしべ長者</h2>

<p>あなたの不要な物は誰かの宝物</p>

<p>物々交換で心をつなぐ地域のコミュニティ</p>

<%= link_to "新規投稿", new_item_path %>

<%= link_to "投稿一覧", items_path %>

app/views/homes/top.html.erb
<p>物と心をつなぐ物々交換</p>

<%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path %>

<%= link_to "ログイン",new_user_session_path %>

<%= link_to "新規登録",new_user_registration_path %>

<%= link_to "ログアウト",destroy_user_session_path %>

<%= link_to "about", about_path %>

app/views/items/index.html.erb
<h2>投稿一覧</h2>

<% @items.each do |item| %>
　<%= item.title %>
　<%= item.body %>
　<% @item.item_images.each do |item_image| %>
　　<%= attachment_image_tag item_image, :image, size: "130x130" %>
　<% end %>
<% end %>

app/views/items/new.html.erb
<h2>新規投稿</h2>

<%= form_with model: @item, url: items_path, local: true do |f| %>
　<%= f.label :"商品"%>
　<%= f.text_field :title %>
　<%= f.label :"商品画像"%>
　<%= f.attachment_field :item_images_images, multiple: true %>
　<%= f.label :"紹介文"%>
　<%= f.text_area :body %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <i class="fab fa-instagram-square fa-2x"></i>
      <i class="fab fa-facebook-square fa-2x"></i>
      <i class="fab fa-twitter-square fa-2x"></i>
    </div>
    <div class="row">
      <p>© 2022 八木陽祐</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6"></div>
    <div class="col-6 col-md-6">
      <ul class="navbar-nav" style="flex-direction: row;">
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete do %>
           ログアウト
          <% end %>
        </li>
     <% else %>
        <li class="nav-item">
          <%= link_to about_path do %>
           About
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path do %>
            新規登録
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path do %>
           ログイン
          <% end %>
        </li>
        <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bartering</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
     
     <%= stylesheet_link_tag 'application', :media => 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <id="notice"><%= notice %></id>
    <%= yield %>
  </body>
  <%= render "layouts/footer" %>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>